default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
#  username: postgresql
#  password: psql
  encoding: unicode

development:
  <<: *default
  database: webspi_development

test:
  <<: *default
  database: webspi_test

production:
  url: <%= ENV['DATABASE_URL'] %>
