default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000
  username: postgresql
  password: psql
  encoding: utf8

development:
  <<: *default
  database: rails_development

test:
  <<: *default
  database: rails_test

production:
  url: <%= ENV['DATABASE_URL'] %>
